name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build # Creates  'dist' folder
        env:
          GOOGLE_TAG_ID: ${{ vars.GOOGLE_TAG_ID }} # Pass the Google Tag ID as an environment variable

      # Now build the docusaurus site and prepare it for deployment to GitHub Pages. The 'dist' folder should contain the compiled static files ready for deployment.
      - name: Build Docusaurus site
        working-directory: web
        run: npm ci && npm run build
        env:
          DOC_GOOGLE_TAG_ID: ${{ vars.DOC_GOOGLE_TAG_ID }} # Pass the Specific Google Tag ID as an environment variable
          ALGOLIA_APP_ID: ${{ vars.ALGOLIA_APP_ID }} # Pass Algolia App ID as an environment variable
          ALGOLIA_API_KEY: ${{ vars.ALGOLIA_API_KEY }} # Pass Algolia API Key as an environment variable
          ALGOLIA_INDEX_NAME: ${{ vars.ALGOLIA_INDEX_NAME }} # Pass Algolia Index Name as an environment variable

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Points to compiled files

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4